# Generated by Django 3.2 on 2022-06-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_first_time',
            field=models.BooleanField(default=True),
        ),
    ]
