# Generated by Django 3.2 on 2022-06-11 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PadhanPathan', '0004_rename_reportquestion_reportcourses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportcourses',
            old_name='question',
            new_name='Course',
        ),
    ]
