# Generated by Django 3.2 on 2022-06-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PadhanPathan', '0005_rename_question_reportcourses_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
