# Generated by Django 3.2 on 2022-06-26 07:47

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PadhanPathan', '0007_attempted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.PositiveIntegerField(default=600)),
                ('attempted', models.BooleanField(default=False)),
                ('answer', ckeditor_uploader.fields.RichTextUploadingField(default='Paste Your Answer in PDF format here', max_length=5000, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('examquestion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PadhanPathan.examquestion')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
